Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -20,9 +20,25 @@ jobs:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
-    # Steps represent a sequence of tasks that will be executed as part of the job
-    steps:
-      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
-              
-                uses: mockoon/cli-action@v2.0.0
-            
+  steps:
+      - name: Check Personal Access Token
+        run: |
+          echo "Checking GitHub Token for expiry and/or access"
+          # prepend some arguments, but pass on whatever arguments this script was called with
+          output="$(curl -XGET \
+          --write '\n%{http_code}\n'  \
+          --silent \
+          --fail -H 'Content-Type:application/json' \
+          -H 'Accept:application/json' \
+          -H 'authorization: token '"${GHBOT_TOKEN}" https://api.github.com/repos/MyOrg/MyRepo \
+          )"
+          return_code=$?
+          if [ 0 -eq $return_code ]; then
+              # remove the "http_code" line from the end of the output, and parse it
+              echo "Yay! Your personal access code is not expired and has access to this repo"
+          else
+              echo "Boo! Your personal access code is expired or has no access"
+             # comment the next line if you don't want to see the HTTP status code and return messages from GitHub
+             echo "Failure: code=$output"
+             exit 1
+          fi
